echo cat.sh
cat cat.sh
echo CMakeLists.txt
cat CMakeLists.txt
echo config/lv_conf_pc.h
cat config/lv_conf_pc.h
echo config/lv_conf_stm32.h
cat config/lv_conf_stm32.h
echo compile.sh
cat compile.sh
echo app/CMakeLists.txt
cat app/CMakeLists.txt
echo app/app.c
cat app/app.c
echo app/app.h
cat app/app.h
echo pc/CMakeLists.txt
cat pc/CMakeLists.txt
echo pc/main_pc.c
cat pc/main_pc.c
echo src/fonts/dejavu_24_ru.c
#cat src/fonts/dejavu_24_ru.c
echo src/fonts/dejavu_28_ru.c
#cat src/fonts/dejavu_28_ru.c
echo stm32/CMakeLists.txt 
cat stm32/CMakeLists.txt
echo stm32/main_stm32.c
cat stm32/main_stm32.c
echo stm32/stm32_port.c
cat stm32/stm32_port.c
echo stm32/stm32_port.h
cat stm32/stm32_port.h
echo stm32/Makefile
cat stm32/Makefile
